package com.Mail.DAO;

import com.Mail.DTO.TBind;

import java.util.List;

import com.Mail.DTO.TBindExample;
import org.apache.ibatis.annotations.Param;

public interface TBindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    int countByExample(TBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    int deleteByExample(TBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    int insert(TBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    int insertSelective(TBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    List<TBind> selectByExample(TBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    TBind selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TBind record, @Param("example") TBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TBind record, @Param("example") TBindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TBind record);
}