package com.Mail.DAO;

import com.Mail.DTO.TMail;

import java.util.List;

import com.Mail.DTO.TMailExample;
import org.apache.ibatis.annotations.Param;

public interface TMailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    int countByExample(TMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    int deleteByExample(TMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    int insert(TMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    int insertSelective(TMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    List<TMail> selectByExample(TMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    TMail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TMail record, @Param("example") TMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TMail record, @Param("example") TMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TMail record);
}