package com.Mail.DTO;

import java.io.Serializable;

public class TBind implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bind.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bind.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bind.user_mail
     *
     * @mbggenerated
     */
    private Integer userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bind.mail_acc
     *
     * @mbggenerated
     */
    private String mailAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bind.mail_auth
     *
     * @mbggenerated
     */
    private String mailAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bind.id
     *
     * @return the value of t_bind.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bind.id
     *
     * @param id the value for t_bind.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bind.user_id
     *
     * @return the value of t_bind.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bind.user_id
     *
     * @param userId the value for t_bind.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bind.user_mail
     *
     * @return the value of t_bind.user_mail
     *
     * @mbggenerated
     */
    public Integer getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bind.user_mail
     *
     * @param userMail the value for t_bind.user_mail
     *
     * @mbggenerated
     */
    public void setUserMail(Integer userMail) {
        this.userMail = userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bind.mail_acc
     *
     * @return the value of t_bind.mail_acc
     *
     * @mbggenerated
     */
    public String getMailAcc() {
        return mailAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bind.mail_acc
     *
     * @param mailAcc the value for t_bind.mail_acc
     *
     * @mbggenerated
     */
    public void setMailAcc(String mailAcc) {
        this.mailAcc = mailAcc == null ? null : mailAcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bind.mail_auth
     *
     * @return the value of t_bind.mail_auth
     *
     * @mbggenerated
     */
    public String getMailAuth() {
        return mailAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bind.mail_auth
     *
     * @param mailAuth the value for t_bind.mail_auth
     *
     * @mbggenerated
     */
    public void setMailAuth(String mailAuth) {
        this.mailAuth = mailAuth == null ? null : mailAuth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TBind other = (TBind) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserMail() == null ? other.getUserMail() == null : this.getUserMail().equals(other.getUserMail()))
            && (this.getMailAcc() == null ? other.getMailAcc() == null : this.getMailAcc().equals(other.getMailAcc()))
            && (this.getMailAuth() == null ? other.getMailAuth() == null : this.getMailAuth().equals(other.getMailAuth()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserMail() == null) ? 0 : getUserMail().hashCode());
        result = prime * result + ((getMailAcc() == null) ? 0 : getMailAcc().hashCode());
        result = prime * result + ((getMailAuth() == null) ? 0 : getMailAuth().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bind
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", userMail=").append(userMail);
        sb.append(", mailAcc=").append(mailAcc);
        sb.append(", mailAuth=").append(mailAuth);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}