package com.Mail.DTO;

import java.io.Serializable;

public class TMail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.mail_name
     *
     * @mbggenerated
     */
    private String mailName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.mail_smtp
     *
     * @mbggenerated
     */
    private String mailSmtp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.mail_pop3
     *
     * @mbggenerated
     */
    private String mailPop3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.mail_pop3_port
     *
     * @mbggenerated
     */
    private String mailPop3Port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mail.mail_smtp_port
     *
     * @mbggenerated
     */
    private String mailSmtpPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.id
     *
     * @return the value of t_mail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.id
     *
     * @param id the value for t_mail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.mail_name
     *
     * @return the value of t_mail.mail_name
     *
     * @mbggenerated
     */
    public String getMailName() {
        return mailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.mail_name
     *
     * @param mailName the value for t_mail.mail_name
     *
     * @mbggenerated
     */
    public void setMailName(String mailName) {
        this.mailName = mailName == null ? null : mailName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.mail_smtp
     *
     * @return the value of t_mail.mail_smtp
     *
     * @mbggenerated
     */
    public String getMailSmtp() {
        return mailSmtp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.mail_smtp
     *
     * @param mailSmtp the value for t_mail.mail_smtp
     *
     * @mbggenerated
     */
    public void setMailSmtp(String mailSmtp) {
        this.mailSmtp = mailSmtp == null ? null : mailSmtp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.mail_pop3
     *
     * @return the value of t_mail.mail_pop3
     *
     * @mbggenerated
     */
    public String getMailPop3() {
        return mailPop3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.mail_pop3
     *
     * @param mailPop3 the value for t_mail.mail_pop3
     *
     * @mbggenerated
     */
    public void setMailPop3(String mailPop3) {
        this.mailPop3 = mailPop3 == null ? null : mailPop3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.mail_pop3_port
     *
     * @return the value of t_mail.mail_pop3_port
     *
     * @mbggenerated
     */
    public String getMailPop3Port() {
        return mailPop3Port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.mail_pop3_port
     *
     * @param mailPop3Port the value for t_mail.mail_pop3_port
     *
     * @mbggenerated
     */
    public void setMailPop3Port(String mailPop3Port) {
        this.mailPop3Port = mailPop3Port == null ? null : mailPop3Port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mail.mail_smtp_port
     *
     * @return the value of t_mail.mail_smtp_port
     *
     * @mbggenerated
     */
    public String getMailSmtpPort() {
        return mailSmtpPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mail.mail_smtp_port
     *
     * @param mailSmtpPort the value for t_mail.mail_smtp_port
     *
     * @mbggenerated
     */
    public void setMailSmtpPort(String mailSmtpPort) {
        this.mailSmtpPort = mailSmtpPort == null ? null : mailSmtpPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TMail other = (TMail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMailName() == null ? other.getMailName() == null : this.getMailName().equals(other.getMailName()))
            && (this.getMailSmtp() == null ? other.getMailSmtp() == null : this.getMailSmtp().equals(other.getMailSmtp()))
            && (this.getMailPop3() == null ? other.getMailPop3() == null : this.getMailPop3().equals(other.getMailPop3()))
            && (this.getMailPop3Port() == null ? other.getMailPop3Port() == null : this.getMailPop3Port().equals(other.getMailPop3Port()))
            && (this.getMailSmtpPort() == null ? other.getMailSmtpPort() == null : this.getMailSmtpPort().equals(other.getMailSmtpPort()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMailName() == null) ? 0 : getMailName().hashCode());
        result = prime * result + ((getMailSmtp() == null) ? 0 : getMailSmtp().hashCode());
        result = prime * result + ((getMailPop3() == null) ? 0 : getMailPop3().hashCode());
        result = prime * result + ((getMailPop3Port() == null) ? 0 : getMailPop3Port().hashCode());
        result = prime * result + ((getMailSmtpPort() == null) ? 0 : getMailSmtpPort().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mailName=").append(mailName);
        sb.append(", mailSmtp=").append(mailSmtp);
        sb.append(", mailPop3=").append(mailPop3);
        sb.append(", mailPop3Port=").append(mailPop3Port);
        sb.append(", mailSmtpPort=").append(mailSmtpPort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}