package com.Mail.DTO;

import java.util.ArrayList;
import java.util.List;

public class TMailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    public TMailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMailNameIsNull() {
            addCriterion("mail_name is null");
            return (Criteria) this;
        }

        public Criteria andMailNameIsNotNull() {
            addCriterion("mail_name is not null");
            return (Criteria) this;
        }

        public Criteria andMailNameEqualTo(String value) {
            addCriterion("mail_name =", value, "mailName");
            return (Criteria) this;
        }

        public Criteria andMailNameNotEqualTo(String value) {
            addCriterion("mail_name <>", value, "mailName");
            return (Criteria) this;
        }

        public Criteria andMailNameGreaterThan(String value) {
            addCriterion("mail_name >", value, "mailName");
            return (Criteria) this;
        }

        public Criteria andMailNameGreaterThanOrEqualTo(String value) {
            addCriterion("mail_name >=", value, "mailName");
            return (Criteria) this;
        }

        public Criteria andMailNameLessThan(String value) {
            addCriterion("mail_name <", value, "mailName");
            return (Criteria) this;
        }

        public Criteria andMailNameLessThanOrEqualTo(String value) {
            addCriterion("mail_name <=", value, "mailName");
            return (Criteria) this;
        }

        public Criteria andMailNameLike(String value) {
            addCriterion("mail_name like", value, "mailName");
            return (Criteria) this;
        }

        public Criteria andMailNameNotLike(String value) {
            addCriterion("mail_name not like", value, "mailName");
            return (Criteria) this;
        }

        public Criteria andMailNameIn(List<String> values) {
            addCriterion("mail_name in", values, "mailName");
            return (Criteria) this;
        }

        public Criteria andMailNameNotIn(List<String> values) {
            addCriterion("mail_name not in", values, "mailName");
            return (Criteria) this;
        }

        public Criteria andMailNameBetween(String value1, String value2) {
            addCriterion("mail_name between", value1, value2, "mailName");
            return (Criteria) this;
        }

        public Criteria andMailNameNotBetween(String value1, String value2) {
            addCriterion("mail_name not between", value1, value2, "mailName");
            return (Criteria) this;
        }

        public Criteria andMailSmtpIsNull() {
            addCriterion("mail_smtp is null");
            return (Criteria) this;
        }

        public Criteria andMailSmtpIsNotNull() {
            addCriterion("mail_smtp is not null");
            return (Criteria) this;
        }

        public Criteria andMailSmtpEqualTo(String value) {
            addCriterion("mail_smtp =", value, "mailSmtp");
            return (Criteria) this;
        }

        public Criteria andMailSmtpNotEqualTo(String value) {
            addCriterion("mail_smtp <>", value, "mailSmtp");
            return (Criteria) this;
        }

        public Criteria andMailSmtpGreaterThan(String value) {
            addCriterion("mail_smtp >", value, "mailSmtp");
            return (Criteria) this;
        }

        public Criteria andMailSmtpGreaterThanOrEqualTo(String value) {
            addCriterion("mail_smtp >=", value, "mailSmtp");
            return (Criteria) this;
        }

        public Criteria andMailSmtpLessThan(String value) {
            addCriterion("mail_smtp <", value, "mailSmtp");
            return (Criteria) this;
        }

        public Criteria andMailSmtpLessThanOrEqualTo(String value) {
            addCriterion("mail_smtp <=", value, "mailSmtp");
            return (Criteria) this;
        }

        public Criteria andMailSmtpLike(String value) {
            addCriterion("mail_smtp like", value, "mailSmtp");
            return (Criteria) this;
        }

        public Criteria andMailSmtpNotLike(String value) {
            addCriterion("mail_smtp not like", value, "mailSmtp");
            return (Criteria) this;
        }

        public Criteria andMailSmtpIn(List<String> values) {
            addCriterion("mail_smtp in", values, "mailSmtp");
            return (Criteria) this;
        }

        public Criteria andMailSmtpNotIn(List<String> values) {
            addCriterion("mail_smtp not in", values, "mailSmtp");
            return (Criteria) this;
        }

        public Criteria andMailSmtpBetween(String value1, String value2) {
            addCriterion("mail_smtp between", value1, value2, "mailSmtp");
            return (Criteria) this;
        }

        public Criteria andMailSmtpNotBetween(String value1, String value2) {
            addCriterion("mail_smtp not between", value1, value2, "mailSmtp");
            return (Criteria) this;
        }

        public Criteria andMailPop3IsNull() {
            addCriterion("mail_pop3 is null");
            return (Criteria) this;
        }

        public Criteria andMailPop3IsNotNull() {
            addCriterion("mail_pop3 is not null");
            return (Criteria) this;
        }

        public Criteria andMailPop3EqualTo(String value) {
            addCriterion("mail_pop3 =", value, "mailPop3");
            return (Criteria) this;
        }

        public Criteria andMailPop3NotEqualTo(String value) {
            addCriterion("mail_pop3 <>", value, "mailPop3");
            return (Criteria) this;
        }

        public Criteria andMailPop3GreaterThan(String value) {
            addCriterion("mail_pop3 >", value, "mailPop3");
            return (Criteria) this;
        }

        public Criteria andMailPop3GreaterThanOrEqualTo(String value) {
            addCriterion("mail_pop3 >=", value, "mailPop3");
            return (Criteria) this;
        }

        public Criteria andMailPop3LessThan(String value) {
            addCriterion("mail_pop3 <", value, "mailPop3");
            return (Criteria) this;
        }

        public Criteria andMailPop3LessThanOrEqualTo(String value) {
            addCriterion("mail_pop3 <=", value, "mailPop3");
            return (Criteria) this;
        }

        public Criteria andMailPop3Like(String value) {
            addCriterion("mail_pop3 like", value, "mailPop3");
            return (Criteria) this;
        }

        public Criteria andMailPop3NotLike(String value) {
            addCriterion("mail_pop3 not like", value, "mailPop3");
            return (Criteria) this;
        }

        public Criteria andMailPop3In(List<String> values) {
            addCriterion("mail_pop3 in", values, "mailPop3");
            return (Criteria) this;
        }

        public Criteria andMailPop3NotIn(List<String> values) {
            addCriterion("mail_pop3 not in", values, "mailPop3");
            return (Criteria) this;
        }

        public Criteria andMailPop3Between(String value1, String value2) {
            addCriterion("mail_pop3 between", value1, value2, "mailPop3");
            return (Criteria) this;
        }

        public Criteria andMailPop3NotBetween(String value1, String value2) {
            addCriterion("mail_pop3 not between", value1, value2, "mailPop3");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortIsNull() {
            addCriterion("mail_pop3_port is null");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortIsNotNull() {
            addCriterion("mail_pop3_port is not null");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortEqualTo(String value) {
            addCriterion("mail_pop3_port =", value, "mailPop3Port");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortNotEqualTo(String value) {
            addCriterion("mail_pop3_port <>", value, "mailPop3Port");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortGreaterThan(String value) {
            addCriterion("mail_pop3_port >", value, "mailPop3Port");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortGreaterThanOrEqualTo(String value) {
            addCriterion("mail_pop3_port >=", value, "mailPop3Port");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortLessThan(String value) {
            addCriterion("mail_pop3_port <", value, "mailPop3Port");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortLessThanOrEqualTo(String value) {
            addCriterion("mail_pop3_port <=", value, "mailPop3Port");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortLike(String value) {
            addCriterion("mail_pop3_port like", value, "mailPop3Port");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortNotLike(String value) {
            addCriterion("mail_pop3_port not like", value, "mailPop3Port");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortIn(List<String> values) {
            addCriterion("mail_pop3_port in", values, "mailPop3Port");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortNotIn(List<String> values) {
            addCriterion("mail_pop3_port not in", values, "mailPop3Port");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortBetween(String value1, String value2) {
            addCriterion("mail_pop3_port between", value1, value2, "mailPop3Port");
            return (Criteria) this;
        }

        public Criteria andMailPop3PortNotBetween(String value1, String value2) {
            addCriterion("mail_pop3_port not between", value1, value2, "mailPop3Port");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortIsNull() {
            addCriterion("mail_smtp_port is null");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortIsNotNull() {
            addCriterion("mail_smtp_port is not null");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortEqualTo(String value) {
            addCriterion("mail_smtp_port =", value, "mailSmtpPort");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortNotEqualTo(String value) {
            addCriterion("mail_smtp_port <>", value, "mailSmtpPort");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortGreaterThan(String value) {
            addCriterion("mail_smtp_port >", value, "mailSmtpPort");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortGreaterThanOrEqualTo(String value) {
            addCriterion("mail_smtp_port >=", value, "mailSmtpPort");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortLessThan(String value) {
            addCriterion("mail_smtp_port <", value, "mailSmtpPort");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortLessThanOrEqualTo(String value) {
            addCriterion("mail_smtp_port <=", value, "mailSmtpPort");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortLike(String value) {
            addCriterion("mail_smtp_port like", value, "mailSmtpPort");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortNotLike(String value) {
            addCriterion("mail_smtp_port not like", value, "mailSmtpPort");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortIn(List<String> values) {
            addCriterion("mail_smtp_port in", values, "mailSmtpPort");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortNotIn(List<String> values) {
            addCriterion("mail_smtp_port not in", values, "mailSmtpPort");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortBetween(String value1, String value2) {
            addCriterion("mail_smtp_port between", value1, value2, "mailSmtpPort");
            return (Criteria) this;
        }

        public Criteria andMailSmtpPortNotBetween(String value1, String value2) {
            addCriterion("mail_smtp_port not between", value1, value2, "mailSmtpPort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}